M48
; DRILL file {KiCad (7.0.0)} date Sun Apr 23 19:10:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-23T19:10:45+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X1.5Y-1.5938
X1.5Y-2.3438
X3.0Y-1.7812
X3.0Y-3.2812
X5.0625Y-2.3438
X5.0625Y-4.2656
T0
M30
